import { existsSync, lstatSync, mkdirSync, readlinkSync, symlinkSync, unlinkSync } from "node:fs"
import { homedir } from "node:os"
import { dirname, join } from "node:path"
import { writeText, BENCH_ROOT, REPO_ROOT } from "./utils"

export type CodexHomeRole = "interceptor" | "axi" | "judge"

const HOMES_ROOT = join(BENCH_ROOT, ".codex-homes")

// The single `interceptor` skill is split into two surface-specific skills.
// The bench exercises browser workflows (SPA reads, network, scene), so the
// browser surface skill is the primary skill to load.
const INTERCEPTOR_SKILL_SRC = join(REPO_ROOT, ".agents", "skills", "interceptor-browser")
const INTERCEPTOR_MACOS_SKILL_SRC = join(REPO_ROOT, ".agents", "skills", "interceptor-macos")
const AXI_SKILL_SRC = join(BENCH_ROOT, "vendor", "axi-skill", "axi")

function ensureDir700(path: string): void {
  mkdirSync(path, { recursive: true, mode: 0o700 })
}

function ensureSymlink(target: string, linkPath: string): void {
  ensureDir700(dirname(linkPath))
  if (existsSync(linkPath) || lstatExists(linkPath)) {
    if (lstatExists(linkPath) && lstatSync(linkPath).isSymbolicLink()) {
      const current = readlinkSync(linkPath)
      if (current === target) return
      unlinkSync(linkPath)
    } else {
      throw new Error(`Refusing to overwrite non-symlink at ${linkPath}`)
    }
  }
  symlinkSync(target, linkPath)
}

function lstatExists(path: string): boolean {
  try {
    lstatSync(path)
    return true
  } catch {
    return false
  }
}

function realCodexAuthSource(): string {
  const codexHome = process.env.CODEX_HOME ?? join(homedir(), ".codex")
  return join(codexHome, "auth.json")
}

function configToml(role: CodexHomeRole): string {
  const header = `# Generated by bench-head-to-head/src/codex-home.ts for role=${role}.
# Do not edit by hand — regenerated on every bench run.
`
  if (role === "axi") {
    return (
      header +
      `
[mcp_servers.chrome-devtools-mcp]
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]
`
    )
  }
  return header
}

export interface CodexHomeProvision {
  path: string
  role: CodexHomeRole
}

export function ensureCodexHome(role: CodexHomeRole): CodexHomeProvision {
  const path = join(HOMES_ROOT, role)
  ensureDir700(path)

  const authSrc = realCodexAuthSource()
  if (existsSync(authSrc)) {
    ensureSymlink(authSrc, join(path, "auth.json"))
  }

  if (role === "interceptor") {
    if (!existsSync(INTERCEPTOR_SKILL_SRC)) {
      throw new Error(`Interceptor skill not found at ${INTERCEPTOR_SKILL_SRC}`)
    }
    ensureSymlink(INTERCEPTOR_SKILL_SRC, join(path, "skills", "interceptor"))
  } else if (role === "axi") {
    if (!existsSync(AXI_SKILL_SRC)) {
      throw new Error(
        `AXI skill not vendored at ${AXI_SKILL_SRC}. See bench-head-to-head/vendor/axi-skill/PROVENANCE.txt for refresh instructions.`,
      )
    }
    ensureSymlink(AXI_SKILL_SRC, join(path, "skills", "axi"))
  }

  writeText(join(path, "config.toml"), configToml(role))

  return { path, role }
}

export function codexHomeForCondition(conditionId: string): CodexHomeProvision {
  if (conditionId === "interceptor") return ensureCodexHome("interceptor")
  if (conditionId === "axi") return ensureCodexHome("axi")
  throw new Error(`No isolated codex home configured for condition ${conditionId}`)
}

export function codexHomeForJudge(): CodexHomeProvision {
  return ensureCodexHome("judge")
}
